name: frontend_template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 5.1.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  awesome_dialog: ^3.2.1 
  email_validator: ^3.0.0
  fluttertoast: ^8.2.5
  animated_tree_view: ^2.2.1
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  fluro: ^2.0.5
  get: ^4.6.6
  go_router: ^14.2.7
  url_strategy: ^0.3.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  webview_flutter_web: ^0.2.2
  webview_flutter: ^4.7.0
  carousel_slider: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
